/**
 * Mock data for demo purposes - CTD Stability Document Generator
 * This provides realistic pharmaceutical stability data for all streams
 */

import type {
  Project,
  DocumentFile,
  Study,
  Lot,
  StorageCondition,
  QualityAttribute,
  PivotedResultView,
  GenerationRun,
  ValidationReport,
  RegulatoryGuideline,
  RegulatoryRule,
  ExtractionJob,
} from '../types';
import type { ReadinessReport } from './client';

// ── Mock Projects ────────────────────────────────────────────────────
export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Amlodipine Besylate DS',
    description: 'Long-term stability program for Amlodipine Besylate drug substance - Phase 3 submission',
    status: 'active',
    clinical_phase: 'phase_3',
    numbering_mode: 'ctd',
    created_by: { id: 'user-1', display_name: 'Dr. Sarah Chen', role: 'author' },
    document_count: 8,
    created_at: '2024-11-15T09:00:00Z',
    updated_at: '2025-01-28T14:30:00Z',
  },
  {
    id: 'proj-002',
    name: 'Metformin HCl Extended Release',
    description: 'Drug product stability study for 500mg and 1000mg ER tablets',
    status: 'active',
    clinical_phase: 'phase_2',
    numbering_mode: 'ctd',
    created_by: { id: 'user-2', display_name: 'Dr. Michael Torres', role: 'author' },
    document_count: 12,
    created_at: '2024-10-20T11:00:00Z',
    updated_at: '2025-01-25T16:45:00Z',
  },
  {
    id: 'proj-003',
    name: 'Lisinopril API Stability',
    description: 'Initial stability data package for IND filing',
    status: 'draft',
    clinical_phase: 'phase_1',
    numbering_mode: 'impd',
    created_by: { id: 'user-1', display_name: 'Dr. Sarah Chen', role: 'author' },
    document_count: 4,
    created_at: '2025-01-10T08:30:00Z',
    updated_at: '2025-01-30T10:00:00Z',
  },
];

// ── Mock Documents ───────────────────────────────────────────────────
export const MOCK_DOCUMENTS: Record<string, DocumentFile[]> = {
  'proj-001': [
    {
      id: 'doc-001',
      filename: 'stability_protocol_v2.pdf',
      original_filename: 'Amlodipine_DS_Stability_Protocol_v2.0.pdf',
      file_type: 'pdf',
      classification: 'stability_plan',
      authority: 'authoritative',
      checksum_sha256: 'abc123...',
      file_size_bytes: 2456000,
      uploaded_at: '2024-11-15T09:15:00Z',
    },
    {
      id: 'doc-002',
      filename: 'stability_report_24m.pdf',
      original_filename: 'Amlodipine_DS_Stability_Report_24Month.pdf',
      file_type: 'pdf',
      classification: 'stability_report',
      authority: 'authoritative',
      checksum_sha256: 'def456...',
      file_size_bytes: 8900000,
      uploaded_at: '2024-12-01T10:30:00Z',
    },
    {
      id: 'doc-003',
      filename: 'coa_batch_A001.pdf',
      original_filename: 'CoA_Batch_A001_Release.pdf',
      file_type: 'pdf',
      classification: 'coa',
      authority: 'supporting',
      checksum_sha256: 'ghi789...',
      file_size_bytes: 450000,
      uploaded_at: '2024-11-20T14:00:00Z',
    },
    {
      id: 'doc-004',
      filename: 'coa_batch_A002.pdf',
      original_filename: 'CoA_Batch_A002_Release.pdf',
      file_type: 'pdf',
      classification: 'coa',
      authority: 'supporting',
      checksum_sha256: 'jkl012...',
      file_size_bytes: 465000,
      uploaded_at: '2024-11-21T09:45:00Z',
    },
    {
      id: 'doc-005',
      filename: 'coa_batch_A003.pdf',
      original_filename: 'CoA_Batch_A003_Release.pdf',
      file_type: 'pdf',
      classification: 'coa',
      authority: 'supporting',
      checksum_sha256: 'mno345...',
      file_size_bytes: 458000,
      uploaded_at: '2024-11-22T11:20:00Z',
    },
    {
      id: 'doc-006',
      filename: 'analytical_methods.pdf',
      original_filename: 'Amlodipine_Analytical_Methods_Validation.pdf',
      file_type: 'pdf',
      classification: 'technical_report',
      authority: 'supporting',
      checksum_sha256: 'pqr678...',
      file_size_bytes: 3200000,
      uploaded_at: '2024-11-18T15:30:00Z',
    },
    {
      id: 'doc-007',
      filename: 'degradation_study.pdf',
      original_filename: 'Forced_Degradation_Study_Report.pdf',
      file_type: 'pdf',
      classification: 'technical_report',
      authority: 'supporting',
      checksum_sha256: 'stu901...',
      file_size_bytes: 4100000,
      uploaded_at: '2024-11-25T13:15:00Z',
    },
    {
      id: 'doc-008',
      filename: 'container_closure.pdf',
      original_filename: 'Container_Closure_Compatibility_Study.pdf',
      file_type: 'pdf',
      classification: 'other_supporting',
      authority: 'supporting',
      checksum_sha256: 'vwx234...',
      file_size_bytes: 1850000,
      uploaded_at: '2024-11-26T10:00:00Z',
    },
  ],
  'proj-002': [
    {
      id: 'doc-101',
      filename: 'metformin_protocol.pdf',
      original_filename: 'Metformin_ER_Stability_Protocol.pdf',
      file_type: 'pdf',
      classification: 'stability_plan',
      authority: 'authoritative',
      checksum_sha256: 'abc111...',
      file_size_bytes: 2100000,
      uploaded_at: '2024-10-20T11:15:00Z',
    },
  ],
  'proj-003': [
    {
      id: 'doc-201',
      filename: 'lisinopril_protocol.pdf',
      original_filename: 'Lisinopril_API_Stability_Protocol_Draft.pdf',
      file_type: 'pdf',
      classification: 'stability_plan',
      authority: 'authoritative',
      checksum_sha256: 'xyz999...',
      file_size_bytes: 1500000,
      uploaded_at: '2025-01-10T08:45:00Z',
    },
  ],
};

// ── Mock Readiness Reports ───────────────────────────────────────────
export const MOCK_READINESS: Record<string, ReadinessReport> = {
  'proj-001': {
    overall_status: 'ready',
    document_summary: {
      total: 8,
      by_classification: {
        stability_plan: 1,
        stability_report: 1,
        coa: 3,
        technical_report: 2,
        other_supporting: 1,
      },
      authoritative_count: 2,
      supporting_count: 6,
    },
    extraction_status: {
      studies: 2,
      conditions: 4,
      attributes: 12,
      extracted: true,
    },
    capabilities: [
      {
        section: '3.2.S.7.1',
        title: 'Stability Summary and Conclusions',
        status: 'ready',
        sources_found: ['stability_report_24m.pdf'],
        missing: [],
      },
      {
        section: '3.2.S.7.2',
        title: 'Post-approval Stability Protocol and Commitment',
        status: 'ready',
        sources_found: ['stability_protocol_v2.pdf'],
        missing: [],
      },
      {
        section: '3.2.S.7.3',
        title: 'Stability Data',
        status: 'ready',
        sources_found: ['stability_report_24m.pdf', 'coa_batch_A001.pdf', 'coa_batch_A002.pdf', 'coa_batch_A003.pdf'],
        missing: [],
      },
    ],
  },
  'proj-002': {
    overall_status: 'partial',
    document_summary: {
      total: 12,
      by_classification: {
        stability_plan: 1,
        stability_report: 2,
        coa: 6,
        technical_report: 2,
        other_supporting: 1,
      },
      authoritative_count: 3,
      supporting_count: 9,
    },
    extraction_status: {
      studies: 3,
      conditions: 5,
      attributes: 15,
      extracted: true,
    },
    capabilities: [
      {
        section: '3.2.P.8.1',
        title: 'Stability Summary and Conclusions',
        status: 'ready',
        sources_found: ['metformin_stability_report.pdf'],
        missing: [],
      },
      {
        section: '3.2.P.8.2',
        title: 'Post-approval Stability Protocol',
        status: 'partial',
        sources_found: ['metformin_protocol.pdf'],
        missing: ['Commitment statement missing'],
      },
      {
        section: '3.2.P.8.3',
        title: 'Stability Data',
        status: 'ready',
        sources_found: ['metformin_stability_report.pdf'],
        missing: [],
      },
    ],
  },
  'proj-003': {
    overall_status: 'blocked',
    document_summary: {
      total: 4,
      by_classification: {
        stability_plan: 1,
        stability_report: 0,
        coa: 2,
        technical_report: 1,
        other_supporting: 0,
      },
      authoritative_count: 1,
      supporting_count: 3,
    },
    extraction_status: {
      studies: 0,
      conditions: 0,
      attributes: 0,
      extracted: false,
    },
    capabilities: [
      {
        section: '2.2.1.S.7',
        title: 'Stability Summary (IMPD)',
        status: 'blocked',
        sources_found: [],
        missing: ['No stability report uploaded', 'Run extraction after uploading stability data'],
      },
      {
        section: '2.2.1.S.7.3',
        title: 'Stability Data (IMPD)',
        status: 'blocked',
        sources_found: [],
        missing: ['Stability report required', 'CoA data incomplete'],
      },
    ],
  },
};

// ── Mock Studies ─────────────────────────────────────────────────────
export const MOCK_STUDIES: Record<string, Study[]> = {
  'proj-001': [
    {
      id: 'study-001',
      product_id: 'prod-001',
      study_type: 'long_term',
      study_label: 'Long-Term Stability Study (25°C/60% RH)',
      protocol_id: 'STAB-AML-001-LT',
      start_date: '2023-01-15',
      sites: ['Site A - Basel, Switzerland'],
      manufacturers: ['PharmaChem GmbH'],
      extraction_status: 'confirmed',
      confidence: 0.95,
      source_anchors: [
        { document_name: 'stability_report_24m.pdf', page: 12, section_ref: '4.1' },
      ],
    },
    {
      id: 'study-002',
      product_id: 'prod-001',
      study_type: 'accelerated',
      study_label: 'Accelerated Stability Study (40°C/75% RH)',
      protocol_id: 'STAB-AML-001-ACC',
      start_date: '2023-01-15',
      sites: ['Site A - Basel, Switzerland'],
      manufacturers: ['PharmaChem GmbH'],
      extraction_status: 'confirmed',
      confidence: 0.92,
      source_anchors: [
        { document_name: 'stability_report_24m.pdf', page: 28, section_ref: '4.2' },
      ],
    },
  ],
  'proj-002': [
    {
      id: 'study-101',
      product_id: 'prod-002',
      study_type: 'long_term',
      study_label: 'Long-Term 500mg ER Tablets',
      protocol_id: 'MET-500-LT-001',
      start_date: '2023-06-01',
      sites: ['Manufacturing Site B'],
      manufacturers: ['TabletCo Inc.'],
      extraction_status: 'confirmed',
      confidence: 0.88,
      source_anchors: [],
    },
    {
      id: 'study-102',
      product_id: 'prod-002',
      study_type: 'accelerated',
      study_label: 'Accelerated 500mg ER Tablets',
      protocol_id: 'MET-500-ACC-001',
      start_date: '2023-06-01',
      sites: ['Manufacturing Site B'],
      manufacturers: ['TabletCo Inc.'],
      extraction_status: 'pending_review',
      confidence: 0.75,
      source_anchors: [],
    },
    {
      id: 'study-103',
      product_id: 'prod-002',
      study_type: 'intermediate',
      study_label: 'Intermediate 1000mg ER Tablets',
      protocol_id: 'MET-1000-INT-001',
      start_date: '2023-08-01',
      sites: ['Manufacturing Site B'],
      manufacturers: ['TabletCo Inc.'],
      extraction_status: 'pending_review',
      confidence: 0.82,
      source_anchors: [],
    },
  ],
};

// ── Mock Lots ────────────────────────────────────────────────────────
export const MOCK_LOTS: Record<string, Lot[]> = {
  'study-001': [
    {
      id: 'lot-001',
      study_id: 'study-001',
      lot_number: 'A001-2023',
      manufacturer: 'PharmaChem GmbH',
      manufacturing_site: 'Basel, Switzerland',
      intended_use: 'Registration batch',
      lot_use_label: 'Primary Stability',
      extraction_status: 'confirmed',
      confidence: 0.96,
    },
    {
      id: 'lot-002',
      study_id: 'study-001',
      lot_number: 'A002-2023',
      manufacturer: 'PharmaChem GmbH',
      manufacturing_site: 'Basel, Switzerland',
      intended_use: 'Registration batch',
      lot_use_label: 'Primary Stability',
      extraction_status: 'confirmed',
      confidence: 0.94,
    },
    {
      id: 'lot-003',
      study_id: 'study-001',
      lot_number: 'A003-2023',
      manufacturer: 'PharmaChem GmbH',
      manufacturing_site: 'Basel, Switzerland',
      intended_use: 'Registration batch',
      lot_use_label: 'Primary Stability',
      extraction_status: 'confirmed',
      confidence: 0.93,
    },
  ],
  'study-002': [
    {
      id: 'lot-004',
      study_id: 'study-002',
      lot_number: 'A001-2023',
      manufacturer: 'PharmaChem GmbH',
      manufacturing_site: 'Basel, Switzerland',
      intended_use: 'Registration batch',
      lot_use_label: 'Accelerated',
      extraction_status: 'confirmed',
      confidence: 0.91,
    },
  ],
};

// ── Mock Storage Conditions ──────────────────────────────────────────
export const MOCK_CONDITIONS: StorageCondition[] = [
  {
    id: 'cond-001',
    label: '25°C ± 2°C / 60% RH ± 5%',
    temperature_setpoint: 25,
    tolerance: '± 2°C',
    humidity: '60% RH ± 5%',
    display_order: 1,
    extraction_status: 'confirmed',
    confidence: 0.98,
  },
  {
    id: 'cond-002',
    label: '30°C ± 2°C / 65% RH ± 5%',
    temperature_setpoint: 30,
    tolerance: '± 2°C',
    humidity: '65% RH ± 5%',
    display_order: 2,
    extraction_status: 'confirmed',
    confidence: 0.97,
  },
  {
    id: 'cond-003',
    label: '40°C ± 2°C / 75% RH ± 5%',
    temperature_setpoint: 40,
    tolerance: '± 2°C',
    humidity: '75% RH ± 5%',
    display_order: 3,
    extraction_status: 'confirmed',
    confidence: 0.96,
  },
  {
    id: 'cond-004',
    label: '5°C ± 3°C (Refrigerated)',
    temperature_setpoint: 5,
    tolerance: '± 3°C',
    humidity: undefined,
    display_order: 4,
    extraction_status: 'pending_review',
    confidence: 0.85,
  },
];

// ── Mock Quality Attributes ──────────────────────────────────────────
export const MOCK_ATTRIBUTES: QualityAttribute[] = [
  {
    id: 'attr-001',
    name: 'Appearance',
    method_group: 'Physical',
    analytical_procedure: 'Visual inspection',
    display_order: 1,
    acceptance_criteria: [{ id: 'ac-001', criteria_text: 'White to off-white crystalline powder' }],
    extraction_status: 'confirmed',
    confidence: 0.99,
  },
  {
    id: 'attr-002',
    name: 'Assay',
    method_group: 'HPLC',
    analytical_procedure: 'USP <621> HPLC Method A',
    display_order: 2,
    acceptance_criteria: [{ id: 'ac-002', criteria_text: '98.0% - 102.0%', lower_limit: 98.0, upper_limit: 102.0, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.97,
  },
  {
    id: 'attr-003',
    name: 'Related Substances (Total)',
    method_group: 'HPLC',
    analytical_procedure: 'USP <621> HPLC Method B',
    display_order: 3,
    acceptance_criteria: [{ id: 'ac-003', criteria_text: 'NMT 1.0%', upper_limit: 1.0, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.95,
  },
  {
    id: 'attr-004',
    name: 'Impurity A',
    method_group: 'HPLC',
    analytical_procedure: 'USP <621> HPLC Method B',
    display_order: 4,
    acceptance_criteria: [{ id: 'ac-004', criteria_text: 'NMT 0.2%', upper_limit: 0.2, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.94,
  },
  {
    id: 'attr-005',
    name: 'Impurity B',
    method_group: 'HPLC',
    analytical_procedure: 'USP <621> HPLC Method B',
    display_order: 5,
    acceptance_criteria: [{ id: 'ac-005', criteria_text: 'NMT 0.15%', upper_limit: 0.15, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.93,
  },
  {
    id: 'attr-006',
    name: 'Any Unspecified Impurity',
    method_group: 'HPLC',
    analytical_procedure: 'USP <621> HPLC Method B',
    display_order: 6,
    acceptance_criteria: [{ id: 'ac-006', criteria_text: 'NMT 0.10%', upper_limit: 0.10, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.92,
  },
  {
    id: 'attr-007',
    name: 'Water Content',
    method_group: 'KF Titration',
    analytical_procedure: 'USP <921> Karl Fischer',
    display_order: 7,
    acceptance_criteria: [{ id: 'ac-007', criteria_text: 'NMT 0.5%', upper_limit: 0.5, unit: '%' }],
    extraction_status: 'confirmed',
    confidence: 0.96,
  },
  {
    id: 'attr-008',
    name: 'Residual Solvents',
    method_group: 'GC',
    analytical_procedure: 'USP <467>',
    display_order: 8,
    acceptance_criteria: [{ id: 'ac-008', criteria_text: 'Meets USP <467> limits' }],
    extraction_status: 'confirmed',
    confidence: 0.91,
  },
  {
    id: 'attr-009',
    name: 'Particle Size D90',
    method_group: 'Laser Diffraction',
    analytical_procedure: 'USP <429>',
    display_order: 9,
    acceptance_criteria: [{ id: 'ac-009', criteria_text: 'NMT 150 µm', upper_limit: 150, unit: 'µm' }],
    extraction_status: 'pending_review',
    confidence: 0.88,
  },
  {
    id: 'attr-010',
    name: 'pH (1% solution)',
    method_group: 'Potentiometry',
    analytical_procedure: 'USP <791>',
    display_order: 10,
    acceptance_criteria: [{ id: 'ac-010', criteria_text: '4.0 - 6.5', lower_limit: 4.0, upper_limit: 6.5 }],
    extraction_status: 'confirmed',
    confidence: 0.94,
  },
  {
    id: 'attr-011',
    name: 'Microbial Limits (TAMC)',
    method_group: 'Microbiology',
    analytical_procedure: 'USP <61>',
    display_order: 11,
    acceptance_criteria: [{ id: 'ac-011', criteria_text: 'NMT 1000 CFU/g', upper_limit: 1000, unit: 'CFU/g' }],
    extraction_status: 'confirmed',
    confidence: 0.90,
  },
  {
    id: 'attr-012',
    name: 'Microbial Limits (TYMC)',
    method_group: 'Microbiology',
    analytical_procedure: 'USP <61>',
    display_order: 12,
    acceptance_criteria: [{ id: 'ac-012', criteria_text: 'NMT 100 CFU/g', upper_limit: 100, unit: 'CFU/g' }],
    extraction_status: 'confirmed',
    confidence: 0.90,
  },
];

// ── Mock Generation Runs ─────────────────────────────────────────────
export const MOCK_GENERATION_RUNS: GenerationRun[] = [
  {
    run_id: 'gen-abc12345',
    status: 'completed',
    outputs: {
      html: '/api/v1/outputs/gen-abc12345/document.html',
      traceability_json: '/api/v1/outputs/gen-abc12345/traceability.json',
    },
    token_usage: {
      input_tokens: 45200,
      output_tokens: 12800,
    },
    created_at: '2025-01-28T14:30:00Z',
    completed_at: '2025-01-28T14:32:15Z',
  },
  {
    run_id: 'gen-def67890',
    status: 'completed',
    outputs: {
      html: '/api/v1/outputs/gen-def67890/document.html',
    },
    token_usage: {
      input_tokens: 42100,
      output_tokens: 11500,
    },
    created_at: '2025-01-25T10:15:00Z',
    completed_at: '2025-01-25T10:17:45Z',
  },
];

// ── Mock Validation Report ───────────────────────────────────────────
export const MOCK_VALIDATION_REPORT: ValidationReport = {
  run_id: 'val-001',
  timestamp: new Date().toISOString(),
  overall_status: 'pass_with_warnings',
  hard_failures: [],
  warnings: [
    {
      rule_id: 'VAL-007',
      rule_name: 'Photostability Data',
      severity: 'soft',
      status: 'warning',
      message: 'Photostability study data not provided. Consider including if applicable per ICH Q1B.',
    },
    {
      rule_id: 'VAL-012',
      rule_name: 'Batch History Completeness',
      severity: 'soft',
      status: 'warning',
      message: 'Manufacturing date not extracted for lot A003-2023. Verify source document.',
    },
  ],
  passed: [
    {
      rule_id: 'VAL-001',
      rule_name: 'Minimum Batches',
      severity: 'hard',
      status: 'pass',
      message: '3 batches provided (minimum 3 required)',
    },
    {
      rule_id: 'VAL-002',
      rule_name: 'Long-Term Conditions',
      severity: 'hard',
      status: 'pass',
      message: 'Long-term study at 25°C/60% RH included',
    },
    {
      rule_id: 'VAL-003',
      rule_name: 'Accelerated Conditions',
      severity: 'hard',
      status: 'pass',
      message: 'Accelerated study at 40°C/75% RH included',
    },
    {
      rule_id: 'VAL-004',
      rule_name: 'Minimum Duration',
      severity: 'hard',
      status: 'pass',
      message: '24-month data available for long-term study',
    },
    {
      rule_id: 'VAL-005',
      rule_name: 'Assay Method Validation',
      severity: 'hard',
      status: 'pass',
      message: 'Analytical method validation report referenced',
    },
    {
      rule_id: 'VAL-006',
      rule_name: 'Acceptance Criteria',
      severity: 'hard',
      status: 'pass',
      message: 'All tested attributes have defined acceptance criteria',
    },
    {
      rule_id: 'VAL-008',
      rule_name: 'Container Closure',
      severity: 'hard',
      status: 'pass',
      message: 'Container closure system documented',
    },
    {
      rule_id: 'VAL-009',
      rule_name: 'Protocol Reference',
      severity: 'hard',
      status: 'pass',
      message: 'Stability protocol document included',
    },
    {
      rule_id: 'VAL-010',
      rule_name: 'Data Integrity',
      severity: 'hard',
      status: 'pass',
      message: 'All stability data points have source references',
    },
    {
      rule_id: 'VAL-011',
      rule_name: 'Out-of-Spec Handling',
      severity: 'hard',
      status: 'pass',
      message: 'No OOS results detected',
    },
  ],
};

// ── Mock Regulatory Guidelines ───────────────────────────────────────
export const MOCK_GUIDELINES: RegulatoryGuideline[] = [
  {
    id: 'guide-001',
    title: 'ICH Q1A(R2) - Stability Testing of New Drug Substances and Products',
    agency: 'ICH',
    document_id: 'Q1A(R2)',
    version: 'Step 4',
    publication_date: '2003-02-06',
    is_active: true,
    original_filename: 'ich_q1a_r2_stability.pdf',
    file_checksum_sha256: 'abc123...',
    allocation_pack_count: 1,
    uploaded_at: '2024-06-15T10:00:00Z',
  },
  {
    id: 'guide-002',
    title: 'ICH Q1B - Photostability Testing',
    agency: 'ICH',
    document_id: 'Q1B',
    version: 'Step 4',
    publication_date: '1996-11-06',
    is_active: true,
    original_filename: 'ich_q1b_photostability.pdf',
    file_checksum_sha256: 'def456...',
    allocation_pack_count: 1,
    uploaded_at: '2024-06-15T10:30:00Z',
  },
  {
    id: 'guide-003',
    title: 'EMA/CHMP/QWP/545525/2017 - Quality Requirements for IMPs',
    agency: 'EMA',
    document_id: 'EMA/CHMP/QWP/545525/2017',
    version: 'Rev. 1',
    publication_date: '2022-03-24',
    is_active: true,
    original_filename: 'ema_impd_quality_guideline.pdf',
    file_checksum_sha256: 'ghi789...',
    allocation_pack_count: 1,
    uploaded_at: '2024-07-20T14:00:00Z',
  },
  {
    id: 'guide-004',
    title: 'ICH Q3A(R2) - Impurities in New Drug Substances',
    agency: 'ICH',
    document_id: 'Q3A(R2)',
    version: 'Step 4',
    publication_date: '2006-10-25',
    is_active: false,
    original_filename: 'ich_q3a_r2_impurities.pdf',
    file_checksum_sha256: 'jkl012...',
    allocation_pack_count: 0,
    uploaded_at: '2024-08-01T09:00:00Z',
  },
];

// ── Mock Regulatory Rules ────────────────────────────────────────────
export const MOCK_RULES: Record<string, RegulatoryRule[]> = {
  'guide-001': [
    {
      id: 'rule-001',
      rule_id_code: 'Q1A-001',
      applies_to: ['DS', 'DP'],
      mapped_app_sections: ['3.2.S.7', '3.2.P.8'],
      requirement_level: 'MUST',
      rule_text: 'Stability testing shall include testing of attributes susceptible to change during storage and likely to influence quality, safety, and/or efficacy.',
      evidence_expected: ['List of tested attributes', 'Justification for selection'],
      ui_fields_required: ['attributes', 'justification'],
      validation_severity: 'BLOCK',
      validation_logic: 'attributes.length >= 1',
      traceability: {
        source_file_id: 'guide-001',
        page: 3,
        section_heading: '2.1 General',
        excerpt_snippet: 'Stability testing shall include testing of those attributes...',
      },
      status: 'confirmed',
    },
    {
      id: 'rule-002',
      rule_id_code: 'Q1A-002',
      applies_to: ['DS'],
      mapped_app_sections: ['3.2.S.7.3'],
      requirement_level: 'MUST',
      rule_text: 'Data from stability studies should be provided on at least three primary batches of the drug substance.',
      evidence_expected: ['Batch numbers', 'Batch sizes', 'Manufacturing dates'],
      ui_fields_required: ['lots'],
      validation_severity: 'BLOCK',
      validation_logic: 'lots.length >= 3',
      traceability: {
        source_file_id: 'guide-001',
        page: 5,
        section_heading: '2.2.1 Drug Substance',
        excerpt_snippet: 'Data from stability studies should be provided on at least three primary batches...',
      },
      status: 'confirmed',
    },
    {
      id: 'rule-003',
      rule_id_code: 'Q1A-003',
      applies_to: ['DS', 'DP'],
      mapped_app_sections: ['3.2.S.7', '3.2.P.8'],
      requirement_level: 'MUST',
      rule_text: 'Long-term testing should cover a minimum of 12 months duration at the time of submission.',
      evidence_expected: ['Study duration', 'Testing timepoints'],
      ui_fields_required: ['study_duration', 'timepoints'],
      validation_severity: 'BLOCK',
      validation_logic: 'study_duration_months >= 12',
      traceability: {
        source_file_id: 'guide-001',
        page: 7,
        section_heading: '2.2.7 Testing Frequency',
        excerpt_snippet: 'Long-term testing should cover a minimum of 12 months...',
      },
      status: 'confirmed',
    },
    {
      id: 'rule-004',
      rule_id_code: 'Q1A-004',
      applies_to: ['DS', 'DP'],
      mapped_app_sections: ['3.2.S.7', '3.2.P.8'],
      requirement_level: 'SHOULD',
      rule_text: 'Accelerated testing conditions of 40°C ± 2°C / 75% RH ± 5% RH should be used.',
      evidence_expected: ['Storage conditions', 'Temperature/humidity records'],
      ui_fields_required: ['conditions'],
      validation_severity: 'WARN',
      validation_logic: 'conditions.includes("40°C/75%RH")',
      traceability: {
        source_file_id: 'guide-001',
        page: 6,
        section_heading: '2.2.3 Storage Conditions',
        excerpt_snippet: 'Accelerated testing conditions of 40°C ± 2°C / 75% RH ± 5% RH...',
      },
      status: 'confirmed',
    },
    {
      id: 'rule-005',
      rule_id_code: 'Q1A-005',
      applies_to: ['DS'],
      mapped_app_sections: ['3.2.S.7.1'],
      requirement_level: 'SHOULD',
      rule_text: 'A retest period should be derived from the stability information.',
      evidence_expected: ['Retest period', 'Statistical analysis'],
      ui_fields_required: ['retest_period'],
      validation_severity: 'WARN',
      validation_logic: 'retest_period !== null',
      traceability: {
        source_file_id: 'guide-001',
        page: 9,
        section_heading: '2.2.9 Evaluation',
        excerpt_snippet: 'A retest period should be derived from the stability information...',
      },
      status: 'pending_review',
    },
    {
      id: 'rule-006',
      rule_id_code: 'Q1A-006',
      applies_to: ['DS', 'DP'],
      mapped_app_sections: ['3.2.S.7', '3.2.P.8'],
      requirement_level: 'MAY',
      rule_text: 'Bracketing and matrixing designs may be applied if justified.',
      evidence_expected: ['Design rationale', 'Statistical justification'],
      ui_fields_required: [],
      validation_severity: 'WARN',
      validation_logic: 'true',
      traceability: {
        source_file_id: 'guide-001',
        page: 11,
        section_heading: 'Annex: Bracketing and Matrixing',
        excerpt_snippet: 'Bracketing and matrixing designs may be applied...',
      },
      status: 'confirmed',
    },
  ],
  'guide-002': [
    {
      id: 'rule-101',
      rule_id_code: 'Q1B-001',
      applies_to: ['DS', 'DP'],
      mapped_app_sections: ['3.2.S.7', '3.2.P.8'],
      requirement_level: 'SHOULD',
      rule_text: 'Photostability testing should be conducted on at least one primary batch.',
      evidence_expected: ['Photostability data', 'Light exposure conditions'],
      ui_fields_required: ['photostability_study'],
      validation_severity: 'WARN',
      validation_logic: 'photostability_study !== null',
      traceability: {
        source_file_id: 'guide-002',
        page: 2,
        section_heading: '1. Introduction',
        excerpt_snippet: 'Photostability testing should be conducted...',
      },
      status: 'confirmed',
    },
  ],
  'guide-003': [
    {
      id: 'rule-201',
      rule_id_code: 'IMPD-001',
      applies_to: ['DS'],
      mapped_app_sections: ['2.2.1.S.7'],
      requirement_level: 'MUST',
      rule_text: 'For Phase I, stability data on the IMP batch(es) used in the clinical trial or on representative batches should be provided.',
      evidence_expected: ['Stability data', 'Batch information'],
      ui_fields_required: ['studies', 'lots'],
      validation_severity: 'BLOCK',
      validation_logic: 'studies.length >= 1',
      traceability: {
        source_file_id: 'guide-003',
        page: 15,
        section_heading: '4.2.1 Drug Substance',
        excerpt_snippet: 'For Phase I, stability data on the IMP batch(es)...',
      },
      status: 'confirmed',
    },
  ],
};

// ── Mock Extraction Job ──────────────────────────────────────────────
export const MOCK_EXTRACTION_JOB: ExtractionJob = {
  job_id: 'extract-001',
  status: 'completed',
  progress: {
    documents_processed: 8,
    documents_total: 8,
  },
  summary: {
    studies_found: 2,
    lots_found: 4,
    conditions_found: 4,
    attributes_found: 12,
    results_found: 156,
    low_confidence_count: 3,
  },
};

// ── Mock Pivoted Result View ─────────────────────────────────────────
export const MOCK_PIVOT_VIEW: PivotedResultView = {
  lot: MOCK_LOTS['study-001'][0],
  condition: MOCK_CONDITIONS[0],
  timepoints: ['Initial', '1M', '3M', '6M', '9M', '12M', '18M', '24M'],
  rows: [
    {
      attribute: { name: 'Appearance', method_group: 'Physical' },
      acceptance_criteria: 'White to off-white crystalline powder',
      values: {
        'Initial': { value: 'White crystalline powder', status: 'pass', confidence: 0.99 },
        '1M': { value: 'White crystalline powder', status: 'pass', confidence: 0.98 },
        '3M': { value: 'White crystalline powder', status: 'pass', confidence: 0.98 },
        '6M': { value: 'White crystalline powder', status: 'pass', confidence: 0.97 },
        '9M': { value: 'White crystalline powder', status: 'pass', confidence: 0.97 },
        '12M': { value: 'White crystalline powder', status: 'pass', confidence: 0.96 },
        '18M': { value: 'White crystalline powder', status: 'pass', confidence: 0.95 },
        '24M': { value: 'Off-white crystalline powder', status: 'pass', confidence: 0.94 },
      },
    },
    {
      attribute: { name: 'Assay', method_group: 'HPLC' },
      acceptance_criteria: '98.0% - 102.0%',
      values: {
        'Initial': { value: '100.2%', status: 'pass', confidence: 0.98 },
        '1M': { value: '100.1%', status: 'pass', confidence: 0.97 },
        '3M': { value: '99.9%', status: 'pass', confidence: 0.97 },
        '6M': { value: '99.7%', status: 'pass', confidence: 0.96 },
        '9M': { value: '99.5%', status: 'pass', confidence: 0.96 },
        '12M': { value: '99.3%', status: 'pass', confidence: 0.95 },
        '18M': { value: '99.0%', status: 'pass', confidence: 0.94 },
        '24M': { value: '98.8%', status: 'pass', confidence: 0.93 },
      },
    },
    {
      attribute: { name: 'Related Substances (Total)', method_group: 'HPLC' },
      acceptance_criteria: 'NMT 1.0%',
      values: {
        'Initial': { value: '0.12%', status: 'pass', confidence: 0.97 },
        '1M': { value: '0.14%', status: 'pass', confidence: 0.96 },
        '3M': { value: '0.18%', status: 'pass', confidence: 0.96 },
        '6M': { value: '0.24%', status: 'pass', confidence: 0.95 },
        '9M': { value: '0.31%', status: 'pass', confidence: 0.94 },
        '12M': { value: '0.38%', status: 'pass', confidence: 0.93 },
        '18M': { value: '0.52%', status: 'pass', confidence: 0.92 },
        '24M': { value: '0.65%', status: 'pass', confidence: 0.91 },
      },
    },
    {
      attribute: { name: 'Water Content', method_group: 'KF Titration' },
      acceptance_criteria: 'NMT 0.5%',
      values: {
        'Initial': { value: '0.08%', status: 'pass', confidence: 0.98 },
        '3M': { value: '0.09%', status: 'pass', confidence: 0.97 },
        '6M': { value: '0.11%', status: 'pass', confidence: 0.96 },
        '12M': { value: '0.14%', status: 'pass', confidence: 0.95 },
        '18M': { value: '0.18%', status: 'pass', confidence: 0.94 },
        '24M': { value: '0.21%', status: 'pass', confidence: 0.93 },
      },
    },
  ],
};
